version: '2'
services:
  inovio-app:
    image: inovio
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://inovio-mysql:3306/inovio?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://inovio-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://inovio-elasticsearch:9200
    ports:
      - 8089:8089
  inovio-mysql:
    extends:
      file: mysql.yml
      service: inovio-mysql
  inovio-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: inovio-elasticsearch
